### ISSUE TITLE
Android studio fail to load project

### ISSUE THREAD

**Issue by mihai1voicescu** [Gurupreet/ComposeCookBook#145]
**Describe the bug**
Latest version of Android studio fails to load project on master.

Note that manually building the project with gradle works.

**To Reproduce**
1. Get the latest version of android studio
2. Open project
3. Load gradle

**Expected behavior**
Project should load but it throws an error:
```
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
com.intellij.openapi.externalSystem.model.ExternalSystemException: This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:258)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:116)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11346489/145083738-cca59c53-7a65-451d-9e7c-214de4b6530c.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version 12.0.1

**Additional context**

Android Studio info:
```
Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin, com.jetbrains.space, com.squareup.sqldelight, org.intellij.plugins.markdown
```

**Comment by yogeshpaliyal** [comment]
@mihai1voicescu  use Android Studio (Beta) Bumblebee

**Comment by Lambert-A** [comment]
The same for me.

**Comment by pesjak** [comment]
I tried loading it in a canary android studio and it failed even after I invalidated caches and restart. But it was a different error. Something about permissions in modules.
