### ISSUE TITLE
Need Tiktok Demo

### ISSUE THREAD

**Issue by XiaoJiangMa** [Gurupreet/ComposeCookBook#147]
Need Tiktok Demo.

**Comment by XiaoJiangMa** [comment]
https://user-images.githubusercontent.com/31342932/173473773-ff4e54f9-5c5b-4732-80c1-e70a33fb8104.mp4

Cannot slide！

**Comment by Gurupreet** [comment]
Let me check on it and fix 👍🏽

**Comment by wiryadev** [comment]
It should be fixed with #150 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/26060382/185757968-75d212a1-e338-4a23-8338-16a280b03fbb.gif)
