### ISSUE TITLE
Scaffold appbar covering content

### ISSUE THREAD

**Issue by junerver** [Gurupreet/ComposeCookBook#149]
**Describe the bug**
Scaffold appbar covering  content

**To Reproduce**
1. clone project
2. open in android studio
3. run app on phone

**Expected behavior**
Display content correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/13448219/185528053-021d6e9d-5ca1-439d-b8bb-e9be13ae3609.png)

**Desktop (please complete the following information):**
 - OS: win 11
 - Android studio: Android Studio Electric Eel | 2022.1.1 Canary 9
 - Java Version:  "11.0.12" 2021-07-20 LTS

**Smartphone (please complete the following information):**
 - Device: mi 10 ultral
 - OS: android 12

I tried it on another device and the same problem occurs，All pages using Scaffold have the problem of appbar covering content

**Comment by wiryadev** [comment]
Workin on it, thanks for the report
