### ISSUE TITLE
add list of challenge UI and contributor try to implement it 

### ISSUE THREAD

**Issue by MahmoudMabrok** [Gurupreet/ComposeCookBook#2]

**Comment by Gurupreet** [comment]
What do you mean by this issue can you describe more ?

**Comment by Gurupreet** [comment]
You can specify Ui you are interested in doing here first then you can go ahead with it.

**Comment by MahmoudMabrok** [comment]
i mean you and other suggest an UI they like to see it Implemented with Compose 
and you and others see this UI and try to make it 

for example one see UI for Instagram home screen and share it here as an Issue or add it to Project tab

**Comment by Gurupreet** [comment]
Ok I will update a list of possible stuff tomorrow. Please feel free to comment down any suggestions.
