### ISSUE TITLE
Deprecated Compose APIs must be replaced with new ones for better version migrations 

### ISSUE THREAD

**Issue by hfrsoussama** [Gurupreet/ComposeCookBook#36]
**Describe the bug**
Deprecated APIs use

**To Reproduce**
run command `./gradlew lint`

**Screenshots**
![Capture d’écran 2020-12-13 à 16 39 51](https://user-images.githubusercontent.com/9051631/102016800-15b25f00-3d63-11eb-91b0-558aecdb0df6.jpg)

**Comment by Gurupreet** [comment]
Yes my AS canary find/replace all not working at the moment sadly. Need to replace it with graphicsLayer.

**Comment by hfrsoussama** [comment]
For the find/replace, it's the shortcut that has changed for the `find in path` feature in new version of intellij. you can change it to use old one from prefs

For the deprecated APIs I'm working on it right now ;)
