### ISSUE TITLE
Create a module per demo or per screen

### ISSUE THREAD

**Issue by GerardPaligot** [Gurupreet/ComposeCookBook#61]
**Is your feature request related to a problem? Please describe.**
When you want to check how a demo or a component are developed, it can be hard with the current architecture.

**Describe the solution you'd like**
Create a module per demo or per screen

**Describe alternatives you've considered**
Create module only for demos.

**Comment by Gurupreet** [comment]
I think it's a great suggestions. Would love to do that for new stuff and hopefully refactor existing one's as well. Feel free to refactor any demo if you would like 👍🏽

**Comment by hfrsoussama** [comment]
Thanks @GerardPaligot for bringing the modularization to light. 

As I intended before to do this refact on the project, I'll try to do it by Monday 🤞

The pre-refact starts with the migration of build scripts to Kotlin DSL in #62

**Comment by GerardPaligot** [comment]
@Gurupreet Great, happy to see that you are open about this enhancement. I'll definitely contribute about this. :)

@hfrsoussama I'm not sure why we need to migrate Gradle scripts from Groovy to Kotlin before this issue but I prefer Kotlin so it is ok. ^^

**Comment by Gurupreet** [comment]
Thanks @hfrsoussama @GerardPaligot 💯 Let's get this done 🥇

**Comment by hfrsoussama** [comment]
@GerardPaligot In my upcoming PR, I'll slightly modify your modules script files to use the new shared module confs script.

Using them will look like this : https://github.com/Gurupreet/ComposeCookBook/blob/refact/base_kotlin_dsl_module_conf/demos/instagram/build.gradle.kts

It will help us share the build logic properly and avoid copy/paste modules configs

**Comment by GerardPaligot** [comment]
Good idea! Didn't take the time to do it.
I'll use your plugin in my next contribution!

**Comment by hfrsoussama** [comment]
No worries ^^ I didn't made the PR before because of a compatibility issue with Kotlin 1.4.32. 

Since now we passed to 1.5.10, I'll bring it to light !

and now I'm rebasing on-top of your latest contribution 😉

**Comment by GerardPaligot** [comment]
Thanks @Gurupreet for the invitation! :)
