### ISSUE TITLE
Project have build errors

### ISSUE THREAD

**Issue by Gurupreet** [Gurupreet/ComposeCookBook#81]
**Describe the bug**
While updating to beta09 I noticed somehow project is not compiling giving multiple build errors on 

Android Studio Bumblebee | 2021.1.1 Canary 2
Build #AI-211.6222.4.2111.7407564

**To Reproduce**
Please check branch : https://github.com/Gurupreet/ComposeCookBook/tree/update/beta09

**Screenshots**
<img width="828" alt="Screenshot 2021-06-18 at 9 41 09 PM" src="https://user-images.githubusercontent.com/4903762/122570619-7b6b0500-d07e-11eb-820a-beefad9c315a.png">

**Comment by Gurupreet** [comment]
@GerardPaligot @hfrsoussama is there something missing on my side I am not able to compile latest main. Can you please try above branch if you still face the issue.

**Comment by GerardPaligot** [comment]
I'm checking tonight (europe timezone) and coming back here to let you know!

**Comment by Gurupreet** [comment]
No worries whenever you have time @GerardPaligot 👍🏽 Happy weekend 💯

**Comment by GerardPaligot** [comment]
I can confirm to you that the project compile on `master` branch but not on `update/beta09` branch.
`pointerInteropFilter` is now protected by `@ExperimentalComposeUiApi` annotation so the project didn't compile anymore.
I pushed a commit on your branch. Everything is fine now. :)

https://github.com/Gurupreet/ComposeCookBook/tree/update/beta09

**Comment by Gurupreet** [comment]
It doesn't compile for me in master either showing above last five errors.  
1:) failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction

2:) .KaptContext (in unnamed module @0x45224ac8) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x45224ac8

I am not sure if it's related to android studio version or some caching I have cleared all cache. Let me check more.

**Comment by hfrsoussama** [comment]
Hello @Gurupreet,

I have just tried to compile master branch and all seams good

**Test on current `master` master (Gradle 7.0)**
- Command line only compilation - ✅
- Android Studio Bumblebee Canary 2 - ✅

**Test on `feat/update_gradle_wrapper_7_1` branch (Gradle 7.1)**
- Command line only compilation - ✅
- Android Studio Bumblebee Canary 2 - ✅
- Build Github CI - ✅

**Helpful verification to do**
- Can you try to build the `feat/update_gradle_wrapper_7_1` branch 
- Can you share please the full error thrown in a command line only compilation `./gradlew assembleDebug --stacktrace`
- What version of Java JDK you are using on your machine ?

**Comment by GerardPaligot** [comment]
Same as @hfrsoussama, everything work for me from CLI or AS Canary 2 with my Macbook Pro or my Windows.
Have you tested with only Gradle CLI? If it works, try to clean caches in your AS Canary 2 instance maybe?

**Comment by Gurupreet** [comment]
Thanks @GerardPaligot @hfrsoussama I think it's related to AS canary cache somehow. I will try cleaning it all up. Thanks for quick help 👍🏽 💯

**Comment by hfrsoussama** [comment]
You are welcome 👍
