### ISSUE TITLE
TextInputs are not editable

### ISSUE THREAD

**Issue by Zoha131** [Gurupreet/ComposeCookBook#9]
I have tried the `TextInputs()` compose. Unfortunately, I can't change the text inside them. For some reason, keyboard input is not reflecting in the TextFields.

**Comment by Gurupreet** [comment]
Hey @zoha131 seems like could be state tied issue. Let me take a look Thanks for raising the issue 👍

**Comment by Gurupreet** [comment]
Hey @zoha131 should be working now you can pull latest changes :smile:
