### ISSUE TITLE
Font Runtime Error

### ISSUE THREAD

**Issue by wiryadev** [Gurupreet/ComposeCookBook#91]
**Describe the bug**
The app force closed the first time it try to launch.

**To Reproduce**
use the latest master branch (by the time this issue created) and run it

**Screenshots**
![image](https://user-images.githubusercontent.com/26060382/123499657-756aba80-d662-11eb-9cbe-4415dd551750.png)

**Additional context**
Here is the full [log](https://pastebin.com/v9Fq9LdG).
It points out to getFontFamily function and i think it is because the `Font` has multiple implementation. See this screenshot:

![image](https://user-images.githubusercontent.com/26060382/123499746-1fe2dd80-d663-11eb-9e67-99118826cdb6.png)

![image](https://user-images.githubusercontent.com/26060382/123499711-df835f80-d662-11eb-8fd1-e364cb5d6c8b.png)

**Comment by wiryadev** [comment]
Tried to update fontAwesomCompose version to 1.0.1-alpha01. The old error is gone, but replaced with this error:
```
java.lang.NoSuchMethodError: No interface method startRestartGroup(ILjava/lang/String;)Landroidx/compose/runtime/Composer; in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/com.guru.composecookbook-WgSDCeCP5Tg7qW3QQga3Ug==/base.apk)
        at com.guru.fontawesomecomposelib.FaIconKt.FaIcon-EfRbmQ0(FaIcon.kt:35)
        at com.guru.composecookbook.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:123)
        at com.guru.composecookbook.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:122)
```

**Comment by Gurupreet** [comment]
Yes I think it's related to versioning let me try to reproduce and check on it :)

**Comment by wiryadev** [comment]
> Yes I think it's related to versioning let me try to reproduce and check on it :)

Thanks for that. Btw, i tried to update [FontAwesomeCompose](https://github.com/Gurupreet/FontAwesomeCompose/pull/3) dependencies versioning. I hope you could check on that :D

**Comment by csf033** [comment]
> **Describe the bug**
> The app force closed the first time it try to launch.
> 
> **To Reproduce**
> use the latest master branch (by the time this issue created) and run it
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/26060382/123499657-756aba80-d662-11eb-9cbe-4415dd551750.png)
> 
> **Additional context**
> Here is the full [log](https://pastebin.com/v9Fq9LdG).
> It points out to getFontFamily function and i think it is because the `Font` has multiple implementation. See this screenshot:
> 
> ![image](https://user-images.githubusercontent.com/26060382/123499746-1fe2dd80-d663-11eb-9e67-99118826cdb6.png)
> 
> ![image](https://user-images.githubusercontent.com/26060382/123499711-df835f80-d662-11eb-8fd1-e364cb5d6c8b.png)

Has the problem been solved?

**Comment by Gurupreet** [comment]
Let me check on this today and try to fix.

**Comment by Gurupreet** [comment]
Updated the fontAwesomeCompose to latest version. This issue should be resolved please try with new changes.

**Comment by wiryadev** [comment]
> Updated the fontAwesomeCompose to latest version. This issue should be resolved please try with new changes.

Thanks, the issue is gone now
