### ISSUE TITLE
Tiktok Demo Error

### ISSUE THREAD

**Issue by wiryadev** [Gurupreet/ComposeCookBook#96]
**Describe the bug**
Tiktok demo can not be accessed and will make the app force closed.

**To Reproduce**
1. Go to 'DemoUI'
2. Click on 'Tiktok'
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/26060382/123728314-400dd900-d8bd-11eb-9701-34a51772381d.png)

![image](https://user-images.githubusercontent.com/26060382/123728389-561b9980-d8bd-11eb-906e-41c3f4764b9c.png)

**Additional context**
For full logcat check this pastebin **[here](https://pastebin.com/wd3JJWGr)**.

**Comment by Gurupreet** [comment]
It could be related to viewmodel version is it still happening on latest version ?

**Comment by wiryadev** [comment]
> It could be related to viewmodel version is it still happening on latest version ?

i think you are right, it fixed in latest version
